apiVersion: v1
kind: Pod
metadata:
  name: git-clone-debugger-https
spec:
  volumes:
  - name: workspace
    emptyDir: {}

  # This is the initContainer we are testing.
  initContainers:
  - name: git-cloner-https
    image: alpine/git # This image includes git
    # This is the new, corrected command from our main.go fix.
    command: ["sh", "-c", "git clone https://$(username):$(token)@github.com/arajsinha/mrm-user-a.git /workspace"]
    # This injects the username and PAT from your Kubernetes secret.
    envFrom:
    - secretRef:
        name: github-credentials
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  
  # The main container just sleeps to keep the pod alive for inspection.
  containers:
  - name: sleeper
    image: alpine:latest
    command: ["sleep", "3600"]
  
  restartPolicy: Never