fsm:
  definition:
    states:
      - ErrorState
      - RegionAActive
      - RegionBActive
      - SwitchingToA
      - SwitchingToB
    triggers:
      external:
        - RegionARecovered
        - RegionAFailed
      internal:
        - SwitchFailed
        - SwitchComplete
  behavior:
    transitions:
      - trigger: RegionAFailed
        changes:
          - { currentState: RegionAActive, nextState: SwitchingToB }
      - trigger: SwitchComplete
        changes:
          - { currentState: SwitchingToB, nextState: RegionBActive }
          - { currentState: SwitchingToA, nextState: RegionAActive }
      - trigger: RegionARecovered
        changes:
          - { currentState: RegionBActive, nextState: SwitchingToA }
    actions:
      - state: ErrorState
        tasks:
      - state: RegionAActive
        tasks:
      - state: RegionBActive
        tasks:
      - state: SwitchingToA
        tasks:
          - id: dns_cname_a
            package: dns-adaptor-route53.so
            method: Execute
            outputVariable: dns_cname_aResult
            context:
              recordName: 'capha.aws.saptfe-demo.com.'
              recordType: 'CNAME'
              targetValue: 'https://tfe-india-genai-dev-harmonized-rag-app-approuter.cfapps.eu10-004.hana.ondemand.com'
              ttl: 60
              secretKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "secretKey" }
              hostedZoneID: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "hostedZoneID" }
              accessKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "accessKey" }
              region: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "region" }
          - id: stop_approuter_secondary_a
            package: cfplugin.so
            method: Execute
            outputVariable: stop_approuter_secondary_aResult
            context:
              appGUID: '5b8cd1d0-7de7-475f-92b5-ffa0194a7cab'
              cfAPI: 'https://api.cf.eu20-001.hana.ondemand.com'
              action: 'stop'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "username" }
          - id: stop_srv_secondary_a
            package: cfplugin.so
            method: Execute
            outputVariable: stop_srv_secondary_aResult
            context:
              appGUID: 'a96e610d-b2b4-4dd2-b950-839d1aaca839'
              cfAPI: 'https://api.cf.eu20-001.hana.ondemand.com'
              action: 'stop'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "username" }
          - id: create_subs_primary_switch
            package: hana-adaptor.so
            method: Execute
            outputVariable: create_subs_primary_switchResult
            dependencies: { tasks: [stop_srv_secondary_a, stop_approuter_secondary_a] }
            context:
              action: 'createRemoteSubscriptions'
              remoteSource: 'RS_CAPRAG'
              targetSchema: '2DC652E3F0B04D1B960694179CA391D1'
              credentials: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/hana/primary", "key": "undefined" }
          - id: delete_subs_primary_verify
            package: hana-adaptor.so
            method: Execute
            outputVariable: delete_subs_primary_verifyResult
            dependencies: { tasks: [create_subs_primary_switch] }
            context:
              action: 'deleteRemoteSubscriptions'
              remoteSource: 'RS_CAPRAG'
              targetSchema: '2DC652E3F0B04D1B960694179CA391D1'
              credentials: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/hana/primary", "key": "undefined" }
          - id: recreate_subs_secondary_for_replication
            package: hana-adaptor.so
            method: Execute
            outputVariable: recreate_subs_secondary_for_replicationResult
            dependencies: { tasks: [delete_subs_primary_verify] }
            context:
              action: 'createRemoteSubscriptions'
              remoteSource: 'RS_CAPRAG'
              targetSchema: '858E8272F0B2422195E519423DE650CD'
              credentials: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/hana/secondary", "key": "undefined" }
          - id: start_srv_primary_switch
            package: cfplugin.so
            method: Execute
            outputVariable: start_srv_primary_switchResult
            dependencies: { tasks: [recreate_subs_secondary_for_replication] }
            context:
              appGUID: '22eebcc1-0e01-49e8-9457-792391104949'
              cfAPI: 'https://api.cf.eu10-004.hana.ondemand.com'
              action: 'start'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "username" }
          - id: start_approuter_primary_switch
            package: cfplugin.so
            method: Execute
            outputVariable: start_approuter_primary_switchResult
            dependencies: { tasks: [start_srv_primary_switch] }
            context:
              appGUID: 'e4da98d3-d2d1-4bd4-b837-ed43e46b27dc'
              cfAPI: 'https://api.cf.eu10-004.hana.ondemand.com'
              action: 'start'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "username" }
      - state: SwitchingToB
        tasks:
          - id: dns_cname_b_switch
            package: dns-adaptor-route53.so
            method: Execute
            outputVariable: dns_cname_b_switchResult
            context:
              recordName: 'capha.aws.saptfe-demo.com.'
              recordType: 'CNAME'
              targetValue: 'https://ci-eu20-ha-harmonized-rag-app-approuter.cfapps.eu20-001.hana.ondemand.com'
              ttl: 60
              secretKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "secretKey" }
              hostedZoneID: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "hostedZoneID" }
              accessKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "accessKey" }
              region: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "region" }
          - id: dns_a_b_switch
            package: dns-adaptor-route53.so
            method: Execute
            outputVariable: dns_a_b_switchResult
            dependencies: { tasks: [dns_cname_b_switch] }
            context:
              recordName: 'api.aws.saptfe-demo.com.'
              recordType: 'A'
              targetValue: '192.0.2.45'
              ttl: 60
              secretKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "secretKey" }
              hostedZoneID: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "hostedZoneID" }
              accessKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "accessKey" }
              region: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "region" }
          - id: dns_srv_b_switch
            package: dns-adaptor-route53.so
            method: Execute
            outputVariable: dns_srv_b_switchResult
            dependencies: { tasks: [dns_a_b_switch] }
            context:
              recordName: '_sip._tcp.caprag.aws.saptfe-demo.com.'
              recordType: 'SRV'
              ttl: 60
              port: 5060
              weight: 5
              priority: 10
              secretKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "secretKey" }
              hostedZoneID: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "hostedZoneID" }
              accessKey: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "accessKey" }
              region: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/aws/route53", "key": "region" }
          - id: stop_approuter_primary_b
            package: cfplugin.so
            method: Execute
            outputVariable: stop_approuter_primary_bResult
            context:
              appGUID: 'e4da98d3-d2d1-4bd4-b837-ed43e46b27dc'
              cfAPI: 'https://api.cf.eu10-004.hana.ondemand.com'
              action: 'stop'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "username" }
          - id: stop_srv_primary_b
            package: cfplugin.so
            method: Execute
            outputVariable: stop_srv_primary_bResult
            context:
              appGUID: '22eebcc1-0e01-49e8-9457-792391104949'
              cfAPI: 'https://api.cf.eu10-004.hana.ondemand.com'
              action: 'stop'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/primary", "key": "username" }
          - id: del_remote_sub_secondary
            package: hana-adaptor.so
            method: Execute
            outputVariable: del_remote_sub_secondaryResult
            dependencies: { tasks: [stop_approuter_primary_b, stop_srv_primary_b] }
            context:
              action: 'deleteRemoteSubscriptions'
              remoteSource: 'RS_CAPRAG'
              targetSchema: '858E8272F0B2422195E519423DE650CD'
              credentials: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/hana/secondary", "key": "undefined" }
          - id: start_srv_switch_secondary
            package: cfplugin.so
            method: Execute
            outputVariable: start_srv_switch_secondaryResult
            dependencies: { tasks: [del_remote_sub_secondary] }
            context:
              appGUID: 'a96e610d-b2b4-4dd2-b950-839d1aaca839'
              cfAPI: 'https://api.cf.eu20-001.hana.ondemand.com'
              action: 'start'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "username" }
          - id: stop_approuter_switch_secondary
            package: cfplugin.so
            method: Execute
            outputVariable: stop_approuter_switch_secondaryResult
            dependencies: { tasks: [start_srv_switch_secondary] }
            context:
              appGUID: '5b8cd1d0-7de7-475f-92b5-ffa0194a7cab'
              cfAPI: 'https://api.cf.eu20-001.hana.ondemand.com'
              action: 'start'
              passwordPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "password" }
              originPath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "origin" }
              usernamePath: { "baoPath": "secret/data/scenarios/{{.ScenarioID}}/cf/secondary", "key": "username" }


              