apiVersion: v1
kind: Service
metadata:
  name: mrm-cell-internal
spec:
  clusterIP: None
  selector:
    app: mrm-cell
  ports:
  - name: peer
    port: 2380
    targetPort: 2380
  - name: client
    port: 2379
    targetPort: 2379
---
apiVersion: v1
kind: Service
metadata:
  name: mrm-cell-public
spec:
  selector:
    app: mrm-cell
  ports:
  - name: http-main
    protocol: TCP
    port: 9081
    targetPort: 9081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mrm-cell
spec:
  serviceName: "mrm-cell-internal"
  replicas: 3
  selector:
    matchLabels:
      app: mrm-cell
  template:
    metadata:
      labels:
        app: mrm-cell
      # --- THIS IS THE FIX ---
      # This annotation tells the Istio sidecar to intelligently handle
      # the Kubernetes readiness probe so it doesn't get blocked.
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      # --- END OF FIX ---
    spec:
      containers:
      - name: mrm-cell-container
        image: arajsinha/mrm-cell-factory:latest
        ports:
        - containerPort: 9081
        - containerPort: 2379
        - containerPort: 2380
        readinessProbe:
          httpGet:
            path: /health
            port: 9081
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        envFrom:
        - secretRef:
            name: mrm-cell-secrets
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
          - "./mrm-cell"
          - "--node-id=$(POD_NAME)"
          - "--host-id=$(POD_NAME).mrm-cell-internal"
          - "--http-port=9081"
          - "--client-port=2379"
          - "--peer-port=2380"
          - "--data-dir=/data/etcd"
          - "--initial-cluster=mrm-cell-0=http://mrm-cell-0.mrm-cell-internal:2380,mrm-cell-1=http://mrm-cell-1.mrm-cell-internal:2380,mrm-cell-2=http://mrm-cell-2.mrm-cell-internal:2380"
        volumeMounts:
        - name: etcd-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi