name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Job 1: Build the main MRM Cell image (Unchanged) ---
      - name: Build and push MRM Cell image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arajsinha/mrm-cell-factory:latest
          build-args: |
            CACHE_BUSTER=${{ github.run_id }}

      # --- Job 2 (NEW): Build and push the MCP Server image ---
      - name: Build and push MCP Server image
        uses: docker/build-push-action@v5
        with:
          # Use the repository root as the build context.
          context: .
          # Explicitly point to the Dockerfile inside the service's directory.
          file: ./mcp-server/Dockerfile
          push: true
          # Give this image its own unique name.
          tags: arajsinha/mrm-mcp-server:latest