name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Job 1: Build and push the main MRM Cell image (This part is unchanged and correct)
      - name: Build and push MRM Cell image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: arajsinha/mrm-cell-factory:latest

      # --- THIS IS THE FIX ---
      # Job 2: Build and push the Config Sync Service image
      - name: Build and push Config Sync Service image
        uses: docker/build-push-action@v5
        with:
          # Use the repository root as the build context.
          context: .
          # Explicitly point to the Dockerfile inside the service's directory.
          file: ./config-sync-service/Dockerfile
          push: true
          # Give this image its own unique name.
          tags: arajsinha/mrm-config-sync-service:latest
      # --- END OF FIX ---