name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Job 1: Build the main MRM Cell Orchestrator image ---
      - name: Build and push MRM Cell image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arajsinha/mrm-cell-factory:latest
          build-args: |
            CACHE_BUSTER=${{ github.run_id }}

      # --- Job 2: Build the MCP Server image ---
      - name: Build and push MCP Server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mcp-server/Dockerfile
          push: true
          tags: arajsinha/mrm-mcp-server:latest

      # --- Job 3 (NEW): Build and push the CrewAI Agent image ---
      - name: Build and push CrewAI Agent image
        uses: docker/build-push-action@v5
        with:
          # The context is the subdirectory where the agent's code lives.
          context: ./crewai-researcher
          push: true
          tags: arajsinha/crewai-researcher:latest